### ISSUE TITLE
"copy" key in collection YAML does not return intended result

### ISSUE THREAD

**Issue by arnoldsandoval** [grow/pygrow#126]
In my collection YAML  I have a key that reads "copy" when I try and display it in my template it prints the following where I should be seeing the value: 

``<built-in method copy of dict object at 0x10652e280>``

Here is the corresponding YAML:

```YAML
$path: /day/1/index.html
$view: /views/day.html

title: Day 1
hero:
  image: /source/images/foo.png
  headline: Day 1
  subheadline: Foo Bar Baz

cards:
  - headline: Hello World!
    copy: Hi!
```

And lastly, this is how im referencing it in my template 

```Jinja
{% for card in doc.cards %}
    <div class="card">
      <h2>{{card.headline}}</h2>
      <p>{{card.card}}</p>
    </div>
{% endfor %}
```

This seems like a bug, but please let me know if i've gone off the rails or am including it incorrectly in my template.
