### ISSUE TITLE
Implement sitemap support

### ISSUE THREAD

**Issue by jeremydw** [grow/pygrow#138]
Grow should be able to autogenerate sitemaps for sites. Sitemaps should be configurable in podspec, and have sane defaults.

An example:

```
sitemap:
  enabled: yes
  path: /sitemap.xml  # Defaults to "/{root}/sitemap.xml"
  collections:  # Defaults to "all collections."
  - pages
  - misc
  - devices
  locales:  # Defaults to "all locales."
  - en
  - fr
```

A user should be able to generate a sitemap by simply adding `sitemap: enabled: yes` to podspec.

**Comment by jeremydw** [comment]
Pages should have the ability to opt-out of being included in the sitemap as well. `$hidden` should do this, for example.

**Comment by WillsB3** [comment]
This is great, +1 to this approach :+1:

**Comment by jeremydw** [comment]
This is implemented, but needs to be documented.

**Comment by WillsB3** [comment]
Just gave this a quick test - The sitemap outputs localhost:8080/path/to/page (when on localhost, which makes sense). However can one specify the domain to be used when building for production? I dug into the Sitemap code and see that it's reading this from the env object. Is it possible to configure envs from within the podspec or can it only be done by passing flags into Grow at the CLI?

**Comment by jeremydw** [comment]
Yep! You can configure the env on a deployment-by-deployment basis. Docs are here: https://grow.io/docs/deployment/#environment however I think we should also explicitly document this in the top-level podspec documentation here: https://grow.io/docs/podspec/.

If you had a deployment named `example`, it might look like this:

```
deployments:
  example:
    destination: local
    keep_control_dir: no
    control_dir: ./private/my-project/
    out_dir: ./www/html/
    env:
      host: example.com
      scheme: https
```
