### ISSUE TITLE
g.static doesn't handle fingerprinted assets

### ISSUE THREAD

**Issue by meizon** [grow/pygrow#158]
If I have a `static_dirs` setup such as:

```
- static_dir: /dist/
  serve_at: /{root}/static/{fingerprint}/
  localization:
    static_dir: /dist/intl/{locale}/
    serve_at: /intl/{locale}/{root}/static/{fingerprint}/
```

And then use `g.static('/dist/img/1.png', locale=doc.locale)` it doesn't find the overridden version in the relevant `intl` folder.
