### ISSUE TITLE
Cannot use {root} path formatter for static_dirs:localization:static_dir

### ISSUE THREAD

**Issue by jeremydw** [grow/pygrow#176]
The following config causes a problem:

```
static_dirs:
- static_dir: /static/
  serve_at: /{root}/
  localization:
    static_dir: /static/intl/{locale}/{root}/  # {root} isn't formatted here.
    serve_at: /intl/{locale}/{root}/
```
