### ISSUE TITLE
Can't translate strings in where content is in /data/ folder

### ISSUE THREAD

**Issue by stevenle** [grow/pygrow#181]
I have content stored in /data/foo.yaml, e.g.:

```yaml
sections:
  hero:
    title@: Local favorites,<br>delivered faster
```

The strings are correctly extracted in the translation files but the translations don't seem to be applied within the template when I do:

```
{% set d = g.doc('/data/foo.yaml') %}
{{_(d.sections.hero.title)}}
```
