### ISSUE TITLE
Gulp preprocessor

### ISSUE THREAD

**Issue by jeremydw** [grow/pygrow#183]
To reduce the amount of typing and CLI interaction, Grow can instrument gulp commands at run and build time.

```
preprocessors:
- kind: gulp
  tasks:
    build: build [default]
    run: watch [default]
```

The preprocessor should raise an error if it's unable to instrument the gulp process (e.g. if it's not installed).
