### ISSUE TITLE
Tags for preprocessors

### ISSUE THREAD

**Issue by stevenle** [grow/pygrow#185]
For preprocessors that use `autorun: false`, it'd be nice to be able to tag them with a certain category so that I can run all of the ones with a tag at a time. E.g., something like:

```yaml
preprocessors:
- name: foo
  kind: google_sheet
  tags:
  - blue
  - green
- name: bar
  kind: google_sheet
  tags:
  - blue
  - red
```

Then running `grow preprocess --tag=blue` would run both `foo` and `bar` but `grow preprocess --tag=green` would only run `foo`.
