### ISSUE TITLE
Implement g.static tag

### ISSUE THREAD

**Issue by jeremydw** [grow/pygrow#88]
To this date, the `g.static` template function has been a stub. We need to support static file localization via `g.static`. Here's a quick sample spec with what I'm thinking. Note that a call to `g.static` would return a StaticFile object, just like how `g.doc` returns a Document object. In both cases, the API is consistent: to get a resource's URL (or path), you use `{{<object>.url.path}}`.

Here's sample usage.

In __podspec.yaml__:

```
static_dirs:
- static_dir: /source/images/
  serve_at: /static/images/
  localization:
    static_dir: /source/images/{locale}/
    serve_at: /intl/{locale}/static/images/
```

In a template:

```
{{g.static(‘/source/images/foo.png’).url.path}}
# /static/images/foo.png

{{g.static(‘/source/images/foo.png’, locale=‘de’).url.path}}
# /intl/de/static/images/foo.png (if a localized file exists)
# /static/images/foo.png (if the file doesn’t exist)
```

Just like `g.doc`, actual usage would look something like this:

```
<img src="{{g.static('/source/images/foo.png').url.path}}">
```
