### ISSUE TITLE
Support documents with localized paths and no base path

### ISSUE THREAD

**Issue by jeremydw** [grow/pygrow#97]
The following configuration should be permitted. We should allow documents to specify localized paths without specifying a base path. This will generate localized documents only, and won't generate a base document if both the document and the blueprint don't have base paths specified.

```
$title: Document
$localization:
  path: /intl/{locale}/foo/
  locales:
  - de
  - fr
  - it
```

**Comment by jeremydw** [comment]
/cc @meizon – We've now added support for generating localized documents *without* corresponding base documents. The way to do this is to configure a `path` only under `$localization` and not at the top-level of a content document or a blueprint file – no need to override or specify a default locale.

Using the following testdata, only a single file at `/intl/de/localized/` is generated:

```
# /content/localized/_blueprint.yaml
title: Localized Collection

# /content/localized/localized.yaml
$title: Localized Document
$localization:
  path: /intl/{locale}/localized/
  locales:
  - de
```

If you would like to also generate a base page, simply add a `$path` to the document or `path` to the blueprint!
